apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: yolo-apples
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: gcr.io/storied-box-435409-f6/yolo-apple:latest
        name: yolo-apples
        resources: {}
        args: ["python", "-m", "torch.distributed.run", "train.py", "--img", "416", "--batch", "16", "--epochs", "10", "--device", "cpu", "--data", "data/data.yaml"]
      restartPolicy: Never
status: {}
